### ISSUE TITLE
File locking does not work on MAC OS 10.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [adda-team/adda#83]
```
Thomas Piechota have reported this issue (
http://groups.google.com/group/adda-discuss/browse_thread/thread/d79cfa0b3ea8a46
8
), resulting in compilation errors.

Probably this is caused by the fact that some POSIX environmental variables
are not defined in MAC OS. Moreover, I am not completely sure that the code
for UNIX implementing file locking will work unmodified for MAC OS. Anyway,
this needs more investigating. 

For now, the workaround is to compile without file locking. To do this
uncomment line “CFLAGS += -DNOT_USE_LOCK” in the Makefile. See section 4.1
of the manual for details.
```

Original issue reported on code.google.com by `yurkin` on 9 Jul 2009 at 3:38
